INFO     root:conftest.py:20 =================单个函数用例开始执行=================
INFO     root:test_01_register.py:58 测试数字和元组数字是否相等！！
ERROR    root:test_01_register.py:62 测试数字和元组数字是否相等失败！！
Traceback (most recent call last):
  File "D:\project\Auto_Api\TestCase\test_01_register.py", line 60, in test_out_function
    assert 3 == (4,)
AssertionError: assert 3 == (4,)
INFO     root:conftest.py:22 =================单个函数用例结束执行=================

INFO     root:conftest.py:14 *************************类下的用例结束*************************